### ISSUE TITLE
fabric8:build 4.0.0-M2 failes with message  Failed to execute the build: Error while trying to build the image: Connection is still allocated

### ISSUE THREAD

**Issue by yonoos** [fabric8io/fabric8-maven-plugin#1468] opened 2018-12-29 19:10 UTC
### Description
running the goal fabric8:build failes with message  Failed to execute the build: Error while trying to build the image: Connection is still allocated
This hapens only starting from version 4.0.0-M2. it is working well in 4.0.0-M1
### Info

* f-m-p version : 4.0.0-M2
* Maven version (`mvn -v`) : Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T20:41:47+02:00)
Maven home: C:\younes\softs\maven\bin\..
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: C:\progra~1\Java\jdk1.8.0_191\jre
Default locale: fr_FR, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows
```

```
* Kubernetes version : v1.11.5
* If it's a bug, how to reproduce : run mvn  clean package fabric8:build
(see attached dockerfile and pom.xml)

[pom.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/2716659/pom.txt)

[dockerfile.txt](https://github.com/fabric8io/fabric8-maven-plugin/files/2716662/dockerfile.txt)

**Comment by rohanKanojia** [comment] 2019-01-02 10:40
@yonoos : Could you please provide some reproducible example project? I tried using your pom but it seems to be dependent on some parent pom of your project.

**Comment by yonoos** [comment] 2019-01-02 11:17
@rohanKanojia : you find attached the full project
[full-test-project.zip](https://github.com/fabric8io/fabric8-maven-plugin/files/2720580/full-test-project.zip)

**Comment by dev-gaur** [comment] 2019-04-02 13:06
```
[dgaur@MiWiFi-R3L-srv jee.test-ear]$ mvn fabric8:build
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] Expected root element 'settings' but found 'servers' (position: START_TAG seen <servers>... @1:9)  @ /home/dgaur/.m2/settings.xml, line 1, column 9
[WARNING] 
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------------< yc:jee.test-ear >---------------------------
[INFO] Building jee.test-ear 1.0-SNAPSHOT
[INFO] --------------------------------[ ear ]---------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:4.0-SNAPSHOT:build (default-cli) @ jee.test-ear ---
[INFO] Failure in determining private key algorithm type, defaulting to RSA 
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Building Docker image in Kubernetes mode
[INFO] Failure in determining private key algorithm type, defaulting to RSA 
[INFO] Failure in determining private key algorithm type, defaulting to RSA 
[INFO] Failure in determining private key algorithm type, defaulting to RSA 
[INFO] Failure in determining private key algorithm type, defaulting to RSA 
[ERROR] F8: Failed to execute the build [Error while trying to build the image]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.597 s
[INFO] Finished at: 2019-04-02T18:28:25+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0-SNAPSHOT:build (default-cli) on project jee.test-ear: Failed to execute the build: Error while trying to build the image: Unable to pull 'jboss/wildfly:13.0.0.Final' from registry 'oracleCloudContainerRegistery' : {"message":"invalid reference format: repository name must be lowercase"} (Internal Server Error: 500) -> [Help 1]
[ERROR] 
```

@yonoos I tried this on your provided project repo. 
If you will look closely, the error message is :
```
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.0-SNAPSHOT:build (default-cli) on project jee.test-ear: Failed to execute the build: Error while trying to build the image: Unable to pull 'jboss/wildfly:13.0.0.Final' from registry 'oracleCloudContainerRegistery' : {"message":"invalid reference format: repository name must be lowercase"} (Internal Server Error: 500) -> [Help 1]
```

The error is with your configuration in pom and set registry name and properties. I tried to build the image with the default docker.io registry and it worked successfully.

Closing this issue.

**Closed by dev-gaur** 2019-04-02 13:06 UTC

**Comment by dev-gaur** [comment] 2019-04-02 13:08
FYI, I tried with the current version of fmp , and not 4.0.0-M2 . I'd suggest you ugrade to our latest release 4.0.
