### ISSUE TITLE
GitEnricher should not warn if not applicable

### ISSUE THREAD

**Issue by davsclaus** [fabric8io/fabric8-maven-plugin#314] opened 2016-09-08 08:30 UTC
If you work on a project that is not in git, you get WARNs

```
[INFO] --- fabric8-maven-plugin:3.1.31:resource (default-cli) @ demo ---
[INFO] F8> Running in Kubernetes mode
[INFO] F8> Running generator spring-boot
[INFO] F8> Running generator java-exec
[INFO] F8> fmp-service: Adding a default Service with ports [8080]
[INFO] F8> fmp-controller: Adding a default Deployment
[INFO] F8> fmp-portname: Adding port name http
[INFO] F8> fmp-portname: Adding port name prometheus
[INFO] F8> fmp-portname: Adding port name jolokia
[WARNING] F8> No .git/config file could be found so cannot annotate kubernetes resources with git commit SHA and branch
[WARNING] F8> No .git/config file could be found so cannot annotate kubernetes resources with git commit SHA and branch
```

We could maybe avoid doing the 2x WARN ?

**Comment by rohanKanojia** [comment] 2018-10-05 18:02
@davsclaus : Hi, I'm not able to reproduce this with 3.5.41 . Are you still facing this issue?

**Comment by rhuss** [comment] 2018-10-06 07:37
tbh, we should avoid this warning and just ignore it. The Git enricher should pick up git information only when its a git project. Let's check this and close the issue if this is the case.

**Closed** 2018-11-05 14:23 UTC
Labels: cat/bug, cat/starter, group/enricher, prio/p1, size/s
