### ISSUE TITLE
Fabric8 compatibility with OpenShift 4

### ISSUE THREAD

**Issue by DhruvM1994** [fabric8io/fabric8-maven-plugin#1744] opened 2019-10-23 13:47 UTC
### Info

* f-m-p version : 4.3.1
* Maven version (`mvn -v`) : 3.6.2

* OpenShift setup and version : 4.x
* If it's a feature request, what is your use case :
I am trying to deploy a Spring-Project to OpenShift 4 using the maven fabric8 plugin.
I was wondering whether the above versoin of fabric8 is compatible with that version of OpenShift.

**Comment by rohanKanojia** [comment] 2019-10-23 13:50
Hmm, I'm not fully sure about Openshift 4 compatibility. I have not tried it so far on Openshift 4.

**Comment by rohanKanojia** [comment] 2019-10-23 15:12
@DhruvM1994 : bdw, Could you please share your logs (with -X enabled) with what error you're facing when using FMP on Openshift 4?

**Comment by DhruvM1994** [comment] 2019-10-23 15:28
Here an excerpt of the logs:

```
[INFO] F8: Starting Build mailgroups-s2i
[ERROR] F8: Build for mailgroups-s2i failed: stream was reset: NO_ERROR
[ERROR] F8: mailgroups-s2i-1		null	null
[ERROR] F8: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:56 min
[INFO] Finished at: 2019-10-23T17:22:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:4.3.1:build (default-cli) on project mailgroups: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Unable to build the image using the OpenShift build service
```

**Comment by rohanKanojia** [comment] 2019-10-24 08:23
Strange, I tried building on Openshift 4 using crc; but I didn't face this error:
```
~/work/repos/fmp-demo-project : $ mvn fabric8:build
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< meetup:random-generator >-----------------------
[INFO] Building random-generator 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- fabric8-maven-plugin:4.4-SNAPSHOT:build (default-cli) @ random-generator ---
[INFO] F8: Running in OpenShift mode
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Container image fabric8/s2i-java:2.3 as base / builder
[INFO] Copying files to /home/rohaan/work/repos/fmp-demo-project/target/docker/meetup/random-generator/0.0.1/build/maven
[INFO] Building tar: /home/rohaan/work/repos/fmp-demo-project/target/docker/meetup/random-generator/0.0.1/tmp/docker-build.tar
[INFO] F8: [meetup/random-generator:0.0.1] "spring-boot": Created docker source tar /home/rohaan/work/repos/fmp-demo-project/target/docker/meetup/random-generator/0.0.1/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig random-generator-s2i for Source build
[INFO] F8: Creating ImageStream random-generator
[INFO] F8: Starting Build random-generator-s2i
[INFO] F8: Waiting for build random-generator-s2i-1 to complete...
[INFO] F8: Caching blobs under "/var/cache/blobs".
[INFO] F8: Getting image source signatures
[INFO] F8: Copying blob sha256:7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f
[INFO] F8: Copying blob sha256:1fdb7be5b7e04d78c06271c1fac140923afd7fceba99e670b43a4caeb9e12fe7
[INFO] F8: Copying blob sha256:e39e0acd05a132f9851ab89aa9c003304acaea15239d98a49e66e1a9c82b897f
[INFO] F8: Copying blob sha256:4b44292fec1d5442d3e34b2c3adb430711d3c231d70954a9d42d2217f959a3a5
[INFO] F8: Copying blob sha256:d6fff4bb0996493ee898ab513fb1570c797d91a2d77365cb8ce60ac995d61bef
[INFO] F8: Copying blob sha256:2fab1038512362e3ecc53bd088d15b573554228e40c3a8c2b6a35dd034319d2e
[INFO] F8: Copying blob sha256:444e42197d037bb691bfd39d27dadfddf260c117e648287ffdc9d06b0deb9d9b
[INFO] F8: Copying blob sha256:279f9e9dbd81ffde465c3613c8d42668fc7f90fcdd0ea2fc096dbe00d422ad3d
[INFO] F8: Copying blob sha256:3b0e4c1fe20d89e41b1a408582ee80141da58e972e1e85bb67a3bbb723ac5ba9
[INFO] F8: Copying blob sha256:edd9a9ea806e66bc81595225cd1eb3587288e91c3f0e7a0e050d090529da899c
[INFO] F8: Copying blob sha256:d4feb2e228a99db66740d8a9716e7b425433cf76c6c96ace4a240a48db221b8a
[INFO] F8: Copying blob sha256:728478adadf64ecda279321079d1a30871f5698a434390e893f4924cc3f3772b
[INFO] F8: Copying blob sha256:e7886c5bdbb9091a5fa49fecb3b38ae3b86b4dc3d898f35868ea304a07858fb1
[INFO] F8: Copying blob sha256:05562722fbe3d386d80195a54e38230f27521c800957f861bbe1f4aa16cee114
[INFO] F8: Copying blob sha256:8700ab630acc9c991fd8c8d432f57f8e667269a84cd6c4af7d4bb526d39a7fbd
[INFO] F8: Copying blob sha256:6df3de21051156aa46c745270ffeaad903d7457901761412c7fdcc175425b11c
[INFO] F8: Copying blob sha256:5d7ab3a9fe79144e76610e53f4ca88facbaa68d78a4d652dd5ec01b502a15eef
[INFO] F8: Copying blob sha256:b1e6f56c9412d73422f3d05a420d8060910afe9df98eab26b64f2419be72b41c
[INFO] F8: Copying blob sha256:86b908ea994135af1d1bebc0376f820b833c710d54db966a6248bfce32a6b0f0
[INFO] F8: Copying blob sha256:5530204593f325c8521f77e253694b97cc5390d1e14d0493c35b0eb75f4bc57e
[INFO] F8: Copying blob sha256:dde9d98ac0071a3ace2bd04b41e99cc440183f7a26083253bb612b9e5955f8ee
[INFO] F8: Copying blob sha256:dd32d2faf9fa4e68f8a7195033339c20be7c43096b490f7e39f9778f2ba56e8b
[INFO] F8: Copying blob sha256:2bea995a93a4fb35fffb148c149f340652271706e452e5f49f7e30988b29fe33
[INFO] F8: Copying blob sha256:b66cdd67f702702aa7ed8edbac84cd97c42e8357a5a519e57d94dc23ad144a64
[INFO] F8: Copying blob sha256:94b14ee1a4420484af51a0ed5b9457c83523b69effdbfa57c0704501f19431e2
[INFO] F8: Copying blob sha256:854b48faa47da5e0268a141d13643359a3c01bbf40ef42361d2ee884715ecdf8
[INFO] F8: Copying config sha256:10a0b9c43308245e87a0fef6a30e759ff18af8412788b28161afe04d02c990aa
[INFO] F8: Writing manifest to image destination
[INFO] F8: Storing signatures
[INFO] F8: Generating dockerfile with builder image fabric8/s2i-java:2.3
[INFO] F8: STEP 1: FROM fabric8/s2i-java:2.3
[INFO] F8: STEP 2: LABEL "io.openshift.build.image"="fabric8/s2i-java:2.3" "io.openshift.build.source-location"="/tmp/build/inputs"
[INFO] F8: STEP 3: ENV JAVA_APP_DIR="/deployments" OPENSHIFT_BUILD_NAME="random-generator-s2i-1" OPENSHIFT_BUILD_NAMESPACE="default"
[INFO] F8: STEP 4: USER root
[INFO] F8: STEP 5: COPY upload/src /tmp/src
[INFO] F8: STEP 6: RUN chown -R 1000:0 /tmp/src
[INFO] F8: time="2019-10-24T08:20:50Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah880652285/mnt/rootfs\": error checking if \"/tmp/buildah880652285/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
[INFO] F8: time="2019-10-24T08:20:50Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah880652285/mnt/rootfs\": error checking if \"/tmp/buildah880652285/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
[INFO] F8: STEP 7: USER 1000
[INFO] F8: STEP 8: RUN /usr/local/s2i/assemble
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: Checking for fat jar archive...
[INFO] F8: Found random-generator-0.0.1.jar...
[INFO] F8: ... done
[INFO] F8: time="2019-10-24T08:20:52Z" level=warning msg="pkg/chroot: error unmounting \"/tmp/buildah074922494/mnt/rootfs\": error checking if \"/tmp/buildah074922494/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
[INFO] F8: time="2019-10-24T08:20:52Z" level=warning msg="pkg/bind: error unmounting \"/tmp/buildah074922494/mnt/rootfs\": error checking if \"/tmp/buildah074922494/mnt/rootfs/sys/fs/cgroup/cpuset\" is mounted: no such file or directory"
[INFO] F8: STEP 9: CMD /usr/local/s2i/run
[INFO] F8: STEP 10: COMMIT temp.builder.openshift.io/default/random-generator-s2i-1:ecb15926
[INFO] F8: Getting image source signatures
[INFO] F8: Copying blob sha256:bcc97fbfc9e1a709f0eb78c1da59caeb65f43dc32cd5deeb12b8c1784e5b8237
[INFO] F8: Copying blob sha256:4dbf6f8e65266ba1033bc933ee4e93e4fd5a5c912fe312ae0bd4b8349315c927
[INFO] F8: Copying blob sha256:f515d4009e192a6828b8cbfe57b44282f3f7f94dd770bc24fbd7667b46104402
[INFO] F8: Copying blob sha256:187068858de1a1bfe819ed2daaedf98165ff4f2fdfa94688a8a210da94d03a5a
[INFO] F8: Copying blob sha256:67f9d5f2d2adc7dc615c7c19bb2d359cc09542507f580aa1063447b11888f2c1
[INFO] F8: Copying blob sha256:b0e776602fb699508f7542ff79226b4989e682fc6e8c9ad333c415036163dada
[INFO] F8: Copying blob sha256:99655d012649feba5723686e613e7043b922763d4eb32bf8e8fbae22197eb422
[INFO] F8: Copying blob sha256:5cf9675b81d43432c669204eaa519cdff16a72ad77840c65422a9140f9069259
[INFO] F8: Copying blob sha256:204e205d6a8324c6f2bf8a87c03da3aae056c7a3a05891e78ae10bb9669ec506
[INFO] F8: Copying blob sha256:44c74b2d9af7905e9a48f6b246fada3954d8bfaffa632b4e3d4544dd7d098e0b
[INFO] F8: Copying blob sha256:b0de499398d7e7688d6dc462fd86c3700e450d71056b0914f20c044ecb3900c8
[INFO] F8: Copying blob sha256:78420d45c69a3114490cd4860235c1be87f4aa1e8e184fb25ae87f90df6a9e5e
[INFO] F8: Copying blob sha256:3a434c575e66c5a1f9fe176493327c1217530137ccb9ce9358ec9eaf15c85f5e
[INFO] F8: Copying blob sha256:2db8eeafbb0b25b92852fe703d16dbac4f4a0e463f414c48622d983ef35c56d8
[INFO] F8: Copying blob sha256:c449eef1f16d06a058450cd46b21c68209faf63df9fafc96beff11b1f6741436
[INFO] F8: Copying blob sha256:f0846f8cd3abd07702a44e64f03fec86d4c1ed62ce34800d966dd612dc9aa706
[INFO] F8: Copying blob sha256:26c09e9455ec6c4f46ebe63c8bd0e66462a66387e84c47b57960903ec561e651
[INFO] F8: Copying blob sha256:b46fa3b23bb587f36e2ddc7302325a0656612d3e25f1014ea1542ef1a7a11f18
[INFO] F8: Copying blob sha256:4cc79f25d469867943caffadc23cbbf04fd0fa197f9970971a895e87e9144c2f
[INFO] F8: Copying blob sha256:836bbeb65dcf9de34a98d9d5014115599a2d0a96f45a2c27467d163e6a2e65a1
[INFO] F8: Copying blob sha256:f38efdc13981a067765e03cbdb73a0396c13f201d60fe2af5587dcf3f2c7e4a8
[INFO] F8: Copying blob sha256:e42b0d9852430bd040f4dd7c456f5e0f8a7610bea08c17d0a8052ca65fcfc7dd
[INFO] F8: Copying blob sha256:e91c797f917d1e3084836cd13ba0d6328951853f08da7d9791af51ce22bcc7e1
[INFO] F8: Copying blob sha256:7d50259746069942dcb4ea1a531ed9d7294f264597519ef328a84cadd66a5a12
[INFO] F8: Copying blob sha256:51386491d44c61f9d5572100154a295567450ffcdaf49a4a3cce1fab90583604
[INFO] F8: Copying blob sha256:5bb5ed700464aea14a6c007e8fea1c7a2dd8776701bb72b91332f3cf9abe7291
[INFO] F8: Copying blob sha256:01e88d48c86f093bae541f0cfb6710937e61cfd954bf0aaeabaf9d41b56af162
[INFO] F8: Copying config sha256:01dc462052455b6cc538dfd209164b2388adc74fe7fb2e2f6de7047cdc6bfb07
[INFO] F8: Writing manifest to image destination
[INFO] F8: Storing signatures
[INFO] F8: 01dc462052455b6cc538dfd209164b2388adc74fe7fb2e2f6de7047cdc6bfb07
[INFO] F8: 
[INFO] F8: Pushing image image-registry.openshift-image-registry.svc:5000/default/random-generator:0.0.1 ...
[INFO] F8: Getting image source signatures
[INFO] F8: Copying blob sha256:7dc0dca2b1516961d6b3200564049db0a6e0410b370bb2189e2efae0d368616f
[INFO] F8: Copying blob sha256:1fdb7be5b7e04d78c06271c1fac140923afd7fceba99e670b43a4caeb9e12fe7
[INFO] F8: Copying blob sha256:2fab1038512362e3ecc53bd088d15b573554228e40c3a8c2b6a35dd034319d2e
[INFO] F8: Copying blob sha256:4b44292fec1d5442d3e34b2c3adb430711d3c231d70954a9d42d2217f959a3a5
[INFO] F8: Copying blob sha256:e39e0acd05a132f9851ab89aa9c003304acaea15239d98a49e66e1a9c82b897f
[INFO] F8: Copying blob sha256:d6fff4bb0996493ee898ab513fb1570c797d91a2d77365cb8ce60ac995d61bef
[INFO] F8: Copying blob sha256:edd9a9ea806e66bc81595225cd1eb3587288e91c3f0e7a0e050d090529da899c
[INFO] F8: Copying blob sha256:3b0e4c1fe20d89e41b1a408582ee80141da58e972e1e85bb67a3bbb723ac5ba9
[INFO] F8: Copying blob sha256:279f9e9dbd81ffde465c3613c8d42668fc7f90fcdd0ea2fc096dbe00d422ad3d
[INFO] F8: Copying blob sha256:444e42197d037bb691bfd39d27dadfddf260c117e648287ffdc9d06b0deb9d9b
[INFO] F8: Copying blob sha256:728478adadf64ecda279321079d1a30871f5698a434390e893f4924cc3f3772b
[INFO] F8: Copying blob sha256:e7886c5bdbb9091a5fa49fecb3b38ae3b86b4dc3d898f35868ea304a07858fb1
[INFO] F8: Copying blob sha256:d4feb2e228a99db66740d8a9716e7b425433cf76c6c96ace4a240a48db221b8a
[INFO] F8: Copying blob sha256:05562722fbe3d386d80195a54e38230f27521c800957f861bbe1f4aa16cee114
[INFO] F8: Copying blob sha256:8700ab630acc9c991fd8c8d432f57f8e667269a84cd6c4af7d4bb526d39a7fbd
[INFO] F8: Copying blob sha256:5d7ab3a9fe79144e76610e53f4ca88facbaa68d78a4d652dd5ec01b502a15eef
[INFO] F8: Copying blob sha256:6df3de21051156aa46c745270ffeaad903d7457901761412c7fdcc175425b11c
[INFO] F8: Copying blob sha256:86b908ea994135af1d1bebc0376f820b833c710d54db966a6248bfce32a6b0f0
[INFO] F8: Copying blob sha256:b1e6f56c9412d73422f3d05a420d8060910afe9df98eab26b64f2419be72b41c
[INFO] F8: Copying blob sha256:5530204593f325c8521f77e253694b97cc5390d1e14d0493c35b0eb75f4bc57e
[INFO] F8: Copying blob sha256:2bea995a93a4fb35fffb148c149f340652271706e452e5f49f7e30988b29fe33
[INFO] F8: Copying blob sha256:dd32d2faf9fa4e68f8a7195033339c20be7c43096b490f7e39f9778f2ba56e8b
[INFO] F8: Copying blob sha256:dde9d98ac0071a3ace2bd04b41e99cc440183f7a26083253bb612b9e5955f8ee
[INFO] F8: Copying blob sha256:94b14ee1a4420484af51a0ed5b9457c83523b69effdbfa57c0704501f19431e2
[INFO] F8: Copying blob sha256:854b48faa47da5e0268a141d13643359a3c01bbf40ef42361d2ee884715ecdf8
[INFO] F8: Copying blob sha256:b66cdd67f702702aa7ed8edbac84cd97c42e8357a5a519e57d94dc23ad144a64
[INFO] F8: Copying blob sha256:01e88d48c86f093bae541f0cfb6710937e61cfd954bf0aaeabaf9d41b56af162
[INFO] F8: Copying config sha256:01dc462052455b6cc538dfd209164b2388adc74fe7fb2e2f6de7047cdc6bfb07
[INFO] F8: Writing manifest to image destination
[INFO] F8: Storing signatures
[INFO] F8: Successfully pushed image-registry.openshift-image-registry.svc:5000/default/random-generator@sha256:c005776834a9e78ac5c45f7e7471d0c2cda2c60ef79647f7884de54e494672ce
[INFO] F8: Push successful
[INFO] F8: Build random-generator-s2i-1 in status Complete
[INFO] F8: Found tag on ImageStream random-generator tag: sha256:c005776834a9e78ac5c45f7e7471d0c2cda2c60ef79647f7884de54e494672ce
[INFO] F8: ImageStream random-generator written to /home/rohaan/work/repos/fmp-demo-project/target/random-generator-is.yml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:39 min
[INFO] Finished at: 2019-10-24T13:51:03+05:30
[INFO] ------------------------------------------------------------------------
~/work/repos/fmp-demo-project : $ 
```

Could you please share a sample project to reproduce your error?
My Openshift version was:
```
~/work/repos/fmp-demo-project : $ crc version
crc version: 1.0.0+575079b
OpenShift version: 4.2.0 (embedded in binary)

```

**Comment by DhruvM1994** [comment] 2019-10-24 08:38
Alternatively, I tried to avoid the fabric8-maven-pluing and deploy the application as a docker-image.

Command:
```oc new-app mailgroups```
Here "mailgroups" is the tag of the image.

Output:
```
W1024 09:31:20.782951    2112 dockerimagelookup.go:236] container image registry lookup failed: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 172.30.0.10:53: server misbehaving
W1024 09:31:21.065839    2112 newapp.go:482] Could not find an image stream match for "mailgroups:latest". Make sure that a Docker image with that tag is available on the node for the deployment to succeed.
--> Found container image a180037 (About an hour old) from  for "mailgroups:latest"

    * This image will be deployed in deployment config "mailgroups"
    * Port 8080/tcp will be load balanced by service "mailgroups"
      * Other containers can access this service through the hostname "mailgroups"
    * WARNING: Image "mailgroups:latest" runs as the 'root' user which may not be permitted by your cluster administrator

--> Creating resources ...
    deploymentconfig.apps.openshift.io "mailgroups" created
    service "mailgroups" created
--> Success
    Application is not exposed. You can expose services to the outside world by executing one or more of the commands below:
     'oc expose svc/mailgroups'
    Run 'oc status' to view your app.
```

**Comment by rohanKanojia** [comment] 2019-10-24 08:55
@DhruvM1994 : Would it be possible for you to share a sample project which repdocuces your error with Fabric8 Maven Plugin?

**Comment by rohanKanojia** [comment] 2019-10-24 09:08
Duplicate of #1736

**Comment by DhruvM1994** [comment] 2019-10-24 13:53
I was not specifying the DNS server in the command ```oc start -n <DNS_Server>```.

**Closed** 2019-10-24 13:54 UTC
