### ISSUE TITLE
K8s: resource fragment containing compute resources for containers triggers a WARNING

### ISSUE THREAD

**Issue by lpzdvd** [fabric8io/fabric8-maven-plugin#1185] opened 2018-02-13 17:45 UTC
### Description

Resource fragments in *deployment.yml* containing compute resources triggers a warning despite it is being deployed properly:

### Info

* f-m-p version : 3.5.34
* Maven version (`mvn -v`) : 3.3.9
* Kubernetes version : v1.8.4+coreos.0

### How to reproduce

Place resource fragment in *src/fabric8/deployment.yml*

```yaml
metadata:
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: ${project.artifactId}-container
          resources:
            requests:
              cpu: 100m
              memory: 64Mi             
            limits:
              cpu: 200m
              memory: 512Mi       
```
Build:

```shell
> mvn clean install fabric8:build -P dev                           
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building message-service 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ message-service ---
[INFO] Deleting /home/david/dev/git/poc-message-service/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ message-service ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 1 resource
[INFO] 
[INFO] --- fabric8-maven-plugin:3.5.34:resource (fmp) @ message-service ---
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-jboss-openjdk8-jdk:1.3 as base / builder
[INFO] F8: using resource templates from /home/david/dev/git/poc-message-service/src/main/fabric8
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-srv-svc.yml resource
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-deploymentconfig.yml resource

[WARNING] F8: Invalid Resource : /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/openshift/message-service-deploymentconfig.yml
[message=.spec.template.spec.containers[0].resources.requests.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.memory: string found, object expected, violation type=type]
[INFO] F8: validating /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/kubernetes/message-service-deployment.yml resource
[WARNING] F8: Invalid Resource : /home/david/dev/git/poc-message-service/target/classes/META-INF/fabric8/kubernetes/message-service-deployment.yml
[message=.spec.template.spec.containers[0].resources.limits.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.memory: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.requests.cpu: string found, object expected, violation type=type]
[message=.spec.template.spec.containers[0].resources.limits.cpu: string found, object expected, violation type=type]
```

Deploy goal works properly and pod description show the selected resources:

```shell
Containers:
  message-service-container:
    Container ID:   docker://4578662f826bed474d606b1683b3673acda0d28af3b63a08e9d15d296ec2ae2a
    Image:          lpzdvd/message-service:1.0
    Image ID:       docker-pullable://lpzdvd/message-service@sha256:5726d126996944004245fd43e3e048cc30ccdbf378dc4a812f1c89ff97cb66bb
    Ports:          8080/TCP, 9779/TCP, 8778/TCP
    State:          Running
      Started:      Tue, 13 Feb 2018 17:35:40 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  512Mi
    Requests:
      cpu:     100m
      memory:  64Mi
```

**Comment by cchet** [comment] 2018-03-10 13:34
I experience the same with persistence volume claims (pvc.yml).

-  OpenShift Master:  v3.6.0+c4dd4cf
-  Kubernetes Master:  v1.6.1+5115d708d7 
-  f-m-p version : 3.5.38
-  Maven version (mvn -v) : 3.3.9

**Comment by dipak-pawar** [comment] 2018-03-27 14:16
@rohanKanojia , @piyush1594 Any updates on this? I am also facing  same issue.

**Fmp version**: `3.5.38`
**minishift version**: `v1.14.0+1ec5877`
**oc version**:
```
oc v3.7.2+282e43f
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://192.168.42.74:8443
openshift v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
```
**Reproducer**
https://github.com/dipak-pawar/ftest-openshift-fabric8-maven-plugin

**Steps to Reproduce**
- `git clone https://github.com/dipak-pawar/ftest-openshift-fabric8-maven-plugin`
- `cd ftest-openshift-fabric8-maven-plugin`
- `mvn package fabric8:resource`

**Comment by rohanKanojia** [comment] 2018-03-30 09:33
Hm, It looks like some problem in schema validator used in ResourceValidator.java : 
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/core/src/main/java/io/fabric8/maven/core/util/validator/ResourceValidator.java#L102
Some fields in JSON schema which is marked as required but in reality, it's not required to provide values for these fields while creating resources. In Openshift documentation, ResourceFieldSelector represents container resources(cpu, memory) and their output format, see [here](https://docs.openshift.com/container-platform/3.6/rest_api/openshift_v1.html#v1-resourcefieldselector). I think we need to add an IgnoreRule for this.

**Closed** 2018-04-13 18:16 UTC
Labels: Bug
