### ISSUE TITLE
Generated image reference in *-deployment.yml contains duplicate registry name

### ISSUE THREAD

**Issue by a3aanwisse** [fabric8io/fabric8-maven-plugin#1365] opened 2018-08-27 09:39 UTC
### Description
When using the following configuration:
```
<images>
  <image>
    <name>${docker.registry.host}/my-project-name/%a:%l</name>
   ...
  </image>
</images>
```
and the property ${docker.registry.host} contains a dot (.) in it's value, the image name appearing in the generated *-deployment.yml for kubernetes contains a duplicate registry name:

```
image: foo.bar/foo.bar/my-project-name/some-service:latest
```

When not having a dot in this name (which is impossible since it refers to a docker registry DNS name... the result is as follows:

```
image: foo/my-project-name/some-service:latest
```
### Info
Going back to f-m-p version 3.5.40 fixes this

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) :
```

```
* Kubernetes / OpenShift setup and version :

**Comment by rohanKanojia** [comment] 2018-08-27 11:12
@a3aanwisse : Oops, this could be a regression due to https://github.com/fabric8io/fabric8-maven-plugin/pull/1321 ;-) . Will fix this asap

**Comment by rohanKanojia** [comment] 2018-08-27 14:01
@a3aanwisse : Could you please provide sample pom to reproduce this?

**Comment by rohanKanojia** [comment] 2018-08-29 13:51
@a3aanwisse : I looked into this issue. Yes, This behaviour got changed after #1167 .Shouldn't you specify `${docker.registry.host}` in `<registry>` field rather than appending in name? for example:
```
    <image>
      <name>${project.artifactId}:${project.version}</name>
      <alias>camel-service</alias>
      <registry>${image.user}</registry>
      <build>
        <from>fabric8/s2i-java:1.2</from>
        <assembly>
          <basedir>/deployments</basedir>
          <descriptorRef>artifact-with-dependencies</descriptorRef>
        </assembly>
        <env>
          <JAVA_LIB_DIR>/deployments</JAVA_LIB_DIR>
          <JAVA_MAIN_CLASS>org.apache.camel.cdi.Main</JAVA_MAIN_CLASS>
        </env>
      </build>
    </image>
```

**Comment by rohanKanojia** [comment] 2018-09-12 10:52
@rhuss : Shall we close this issue? WDYT?

**Comment by rhuss** [comment] 2018-09-21 13:15
@rohanKanojia it legitimate to have the registry in the name, too (in that case a configured `<registry>` would be ignored).

A reason is sometimes that you have a property like `${namePrefix}="index.docker.io/"` and could use in images like `<name?${namePrefix}myuser/myimage:1.2</name>`

We used that kind of trick before, not sure whether its still needed. But we should support this, so would be interesting to reproduce this issue.

**Closed** 2018-09-30 07:46 UTC
