### ISSUE TITLE
build failed: Failed to parse ipAddresskubernetes.default.svc: Unknown host kubernetes.default.svc: Name or service not known

### ISSUE THREAD

**Issue by chirino** [fabric8io/fabric8-maven-plugin#1389] opened 2018-09-18 20:56 UTC
### Description
PR build failed on circle ci: https://circleci.com/gh/Apicurio/apicurito/18#tests/containers/0
Changing versions to 3.5.33 made the build work.

### Info

* f-m-p version : 3.5.41
```
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/maven-artifact/3.3.1/maven-artifact-3.3.1.jar (55 kB at 100 kB/s)
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[INFO] F8: Building Docker image in Kubernetes mode
[WARNING] Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] apicurito 1.0.0-SNAPSHOT ........................... SUCCESS [  2.982 s]
[INFO] apicurito-ui 1.0.0-SNAPSHOT ........................ FAILURE [04:38 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:41 min
[INFO] Finished at: 2018-09-18T18:44:10Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (exec) on project apicurito-ui: Execution exec of goal io.fabric8:fabric8-maven-plugin:3.5.41:build failed: Failed to parse ipAddresskubernetes.default.svc: Unknown host kubernetes.default.svc: Name or service not known -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apicurito-ui
```
* Kubernetes / OpenShift setup and version :
* If it's a bug, how to reproduce : build docker image on circleci with 3.5.41
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by rhuss** [comment] 2018-09-19 09:10
Please fix for 3.5.x and master

**Comment by rohanKanojia** [comment] 2018-09-19 10:07
I'm able to reproduce this issue, but not locally only on [CircleCI](https://circleci.com/gh/rohanKanojia/apicurito/3). 

logs of building locally: https://gist.githubusercontent.com/rohanKanojia/284ffa17394f62299d435d5c9a599959/raw/818c168e66c8daa6e837c73baaceeb27bd38d7c3/Build%2520locally

Here is the stacktrace on CircleCI build:
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:46 min
[INFO] Finished at: 2018-09-19T09:37:47Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (exec) on project apicurito-ui: Execution exec of goal io.fabric8:fabric8-maven-plugin:3.5.41:build failed: Failed to parse ipAddresskubernetes.default.svc: Unknown host kubernetes.default.svc: Name or service not known -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.fabric8:fabric8-maven-plugin:3.5.41:build (exec) on project apicurito-ui: Execution exec of goal io.fabric8:fabric8-maven-plugin:3.5.41:build failed: Failed to parse ipAddresskubernetes.default.svc
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution exec of goal io.fabric8:fabric8-maven-plugin:3.5.41:build failed: Failed to parse ipAddresskubernetes.default.svc
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IllegalArgumentException: Failed to parse ipAddresskubernetes.default.svc
    at io.fabric8.kubernetes.client.utils.IpAddressMatcher.parseAddress (IpAddressMatcher.java:95)
    at io.fabric8.kubernetes.client.utils.IpAddressMatcher.matches (IpAddressMatcher.java:57)
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUrl (HttpClientUtils.java:192)
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient (HttpClientUtils.java:142)
    at io.fabric8.kubernetes.client.BaseClient.<init> (BaseClient.java:55)
    at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init> (DefaultKubernetesClient.java:49)
    at io.fabric8.maven.core.access.ClusterAccess.createKubernetesClient (ClusterAccess.java:72)
    at io.fabric8.maven.core.access.ClusterAccess.isOpenShift (ClusterAccess.java:109)
    at io.fabric8.maven.core.access.ClusterAccess.createDefaultClient (ClusterAccess.java:64)
    at io.fabric8.maven.core.service.Fabric8ServiceHub.init (Fabric8ServiceHub.java:84)
    at io.fabric8.maven.core.service.Fabric8ServiceHub.access$1100 (Fabric8ServiceHub.java:39)
    at io.fabric8.maven.core.service.Fabric8ServiceHub$Builder.build (Fabric8ServiceHub.java:198)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.getFabric8ServiceHub (BuildMojo.java:368)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.getGeneratorContext (BuildMojo.java:357)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.customizeConfig (BuildMojo.java:332)
    at io.fabric8.maven.docker.config.ConfigHelper.resolveImages (ConfigHelper.java:51)
    at io.fabric8.maven.docker.AbstractDockerMojo.initImageConfiguration (AbstractDockerMojo.java:308)
    at io.fabric8.maven.docker.AbstractDockerMojo.execute (AbstractDockerMojo.java:215)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute (BuildMojo.java:207)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.net.UnknownHostException: kubernetes.default.svc: Name or service not known
    at java.net.Inet4AddressImpl.lookupAllHostAddr (Native Method)
    at java.net.InetAddress$2.lookupAllHostAddr (InetAddress.java:928)
    at java.net.InetAddress.getAddressesFromNameService (InetAddress.java:1323)
    at java.net.InetAddress.getAllByName0 (InetAddress.java:1276)
    at java.net.InetAddress.getAllByName (InetAddress.java:1192)
    at java.net.InetAddress.getAllByName (InetAddress.java:1126)
    at java.net.InetAddress.getByName (InetAddress.java:1076)
    at io.fabric8.kubernetes.client.utils.IpAddressMatcher.parseAddress (IpAddressMatcher.java:93)
    at io.fabric8.kubernetes.client.utils.IpAddressMatcher.matches (IpAddressMatcher.java:57)
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUrl (HttpClientUtils.java:192)
    at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient (HttpClientUtils.java:142)
    at io.fabric8.kubernetes.client.BaseClient.<init> (BaseClient.java:55)
    at io.fabric8.kubernetes.client.DefaultKubernetesClient.<init> (DefaultKubernetesClient.java:49)
    at io.fabric8.maven.core.access.ClusterAccess.createKubernetesClient (ClusterAccess.java:72)
    at io.fabric8.maven.core.access.ClusterAccess.isOpenShift (ClusterAccess.java:109)
    at io.fabric8.maven.core.access.ClusterAccess.createDefaultClient (ClusterAccess.java:64)
    at io.fabric8.maven.core.service.Fabric8ServiceHub.init (Fabric8ServiceHub.java:84)
    at io.fabric8.maven.core.service.Fabric8ServiceHub.access$1100 (Fabric8ServiceHub.java:39)
    at io.fabric8.maven.core.service.Fabric8ServiceHub$Builder.build (Fabric8ServiceHub.java:198)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.getFabric8ServiceHub (BuildMojo.java:368)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.getGeneratorContext (BuildMojo.java:357)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.customizeConfig (BuildMojo.java:332)
    at io.fabric8.maven.docker.config.ConfigHelper.resolveImages (ConfigHelper.java:51)
    at io.fabric8.maven.docker.AbstractDockerMojo.initImageConfiguration (AbstractDockerMojo.java:308)
    at io.fabric8.maven.docker.AbstractDockerMojo.execute (AbstractDockerMojo.java:215)
    at io.fabric8.maven.plugin.mojo.build.BuildMojo.execute (BuildMojo.java:207)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:954)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :apicurito-ui
```

**Comment by rhuss** [comment] 2018-09-19 11:15
IMO the error occurs if `no.proxy` as property is set to an hostname which cannot be resolved. In this case, and for some reason, its `kubernetes.default.svc` which obviously can be only resolved if the kubernetes client is called from within a Kubernetes cluster.

Two things should be checked:

* Where does this `kubernetes.default.svc` comes from ?
* https://github.com/fabric8io/kubernetes-client/blob/v3.2.0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/utils/IpAddressMatcher.java#L95 should be fixed to not throw an exception on an unresolved hostname, but the matcher should just return `false`.

**Comment by rohanKanojia** [comment] 2018-09-26 09:10
Shall we close this issue? Since the fix is merged in kubernetes client.

**Comment by rhuss** [comment] 2018-09-26 09:56
If f-m-p is upgraded to this new client, then we can close that issue.

**Comment by rohanKanojia** [comment] 2018-10-12 20:43
fmp is upgraded to latest client , closing this now

**Closed by rohanKanojia** 2018-10-12 20:43 UTC
Labels: cat/bug, target/3.5, target/4.0

**Comment by javaHelper** [comment] 2020-04-16 19:44
Could you please guide me here https://stackoverflow.com/questions/61258769/java-lang-illegalargumentexception-failed-to-parse-ipaddresskubernetes-default ?
