### ISSUE TITLE
annoying stacktrace in build log

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1236] opened 2018-03-16 14:23 UTC
### Description
In S2I build FMP shows error stacktrace. It's not failing the build but it would be better to disable it or show one line message
### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 
```
Mar 16, 2018 2:18:26 PM okhttp3.internal.platform.Platform log
WARNING: A connection to https://kubernetes.default.svc/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
[INFO] F8: 
[INFO] F8: Pushing image 172.30.98.11:5000/hshinde-jenkins/vertx-run-test:1.0.13 ...
[INFO] F8: Pushed 5/6 layers, 84% complete
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] F8: Pushed 6/6 layers, 100% complete
[INFO] F8: Push successful
[INFO] F8: Build vertx-run-test-s2i-2 Complete
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[ERROR] Exception in reconnect
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@1b8b45e rejected from java.util.concurrent.ScheduledThreadPoolExecutor@ba248d[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 6]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:729)
	at io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager$3.run(WatchHTTPManager.java:207)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[INFO] F8: Found tag on ImageStream vertx-run-test tag: sha256:c3ad23ece5a809cc4ace4cf08bcb72dc4cec6ce10593d7f51a4487fbf0dd4ff1
[INFO] F8: ImageStream vertx-run-test written to /home/jenkins/workspace/ishin_vertx-run-test_master-EF65ZKBFXOPAR7CQE5OU4JOQHNISLDKYSBFKMLVEAQLYSYUOJNGQ/target/vertx-run-test-is.yml```

```
* Kubernetes / OpenShift setup and version : OS 3.7
* If it's a bug, how to reproduce : `mvn deploy`
* If it's a feature request, what is your use case :
* Sample project : *[GitHub Clone URL]*

**Comment by piyush1594** [comment] 2018-03-16 14:27
This has already been filed here #1159

**Comment by rohanKanojia** [comment] 2018-03-16 14:29
Duplicate of #1159

**Comment by piyush1594** [comment] 2018-04-19 04:53
This has been fixed in client and will be fixed as we upgrade to client

**Closed by piyush1594** 2018-04-19 04:53 UTC
