### ISSUE TITLE
fabric8:deploy specifies wrong version in deployment manifest

### ISSUE THREAD

**Issue by gintautassulskus** [fabric8io/fabric8-maven-plugin#1244] opened 2018-03-24 13:06 UTC
### Description

A project is successfully deployed to local `minikube` when I execute `fabric8:resource`, `fabric8:build` and `fabric8:deploy` goals at once: 
`mvn fabric8:resource fabric8:build fabric8:deploy`

If I run commands separately as follows:
```
mvn fabric8:resource
mvn fabric8:build
mvn fabric8:deploy
```
then pod fails to start with `ImagePullBackOff` due to a wrong version specified in the deployment manifest: `bla-container:snapshot-180324-122854-0943`.
The digit part differs from the one generated by the `build` goal.

Do I need to set some sort of a parameter for `mvn fabric8:deploy` for it to pick up the latest available build in `target` folder?

### Info

* f-m-p version : 3.5.38
* Maven version (`mvn -v`) : 3.5.3
```

```
* Kubernetes / OpenShift setup and version : k8s 1.9.0

**Comment by piyush1594** [comment] 2018-03-24 13:59
Hey 

Try this order, 

```
mvn fabric8:build
mvn fabric8:resource
mvn fabric8:deploy
```

**Comment by gintautassulskus** [comment] 2018-03-24 14:10
Thanks, @piyush1594, this seems to be working. 
But why then the following fails (swapped `build` and `resource` in places) with the same error as in the original post?
`mvn fabric8:build fabric8:resource fabric8:deploy`

**Comment by piyush1594** [comment] 2018-03-24 14:19
Hey @gintautassulskus 

This looks to be some issue, needs to look into this. 

Thanks

**Comment by piyush1594** [comment] 2018-03-25 09:38
#1093 is the original issue related to this which is already in the priority list.

**Comment by rohanKanojia** [comment] 2018-03-27 10:11
Duplicate of #1093

**Comment by pradeepto** [comment] 2018-03-27 10:31
Closing as duplicate.

**Closed by pradeepto** 2018-03-27 10:31 UTC
