### ISSUE TITLE
Add Java 11 support

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1478] opened 2019-01-09 09:29 UTC

**Comment by rohanKanojia** [comment] 2019-02-28 13:19
Duplicate of #1472

**Comment by rohanKanojia** [comment] 2019-05-29 14:03
I think we should prioritize this @lordofthejars @dev-gaur WDYT??

**Comment by dev-gaur** [comment] 2019-06-20 14:06
Closing as fixed.

**Closed by dev-gaur** 2019-06-20 14:06 UTC
