### ISSUE TITLE
Support for resource type kind:PrometheusRule

### ISSUE THREAD

**Issue by jsjjdzg** [fabric8io/fabric8-maven-plugin#1377] opened 2018-09-12 09:49 UTC
**Description**
Trying to use the PrometheusRule resource fails, even when placed in the raw folder.

**Info**
f-m-p version : 4.0.5

Maven version (mvn -v) : 3.3.9

Kubernetes / OpenShift setup and version : OpenShift 3.9

If it's a bug, how to reproduce :
Try to create a resource of kind PrometheusRule, e.g.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

Output:

io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:131)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:93)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:181)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.<init>(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:167)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient$1.<init>(DefaultKubernetesClient.java:114)
	at io.fabric8.kubernetes.client.DefaultKubernetesClient.load(DefaultKubernetesClient.java:114)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.load(DefaultOpenShiftClient.java:225)
	at dzg.TestOkHttp.test3(TestOkHttp.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:monitoring.coreos.com/v1#PrometheusRule
 at [Source: java.io.BufferedInputStream@6443b128; line: 773, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:883)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1575)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1166)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:129)
	... 30 more

**Comment by rhuss** [comment] 2018-09-12 11:02
I dont know how the Kubernetes client is handling Custom Resources (which PrometheusRule is). For sure it can't map it to a model object as its not known to the client.

@rohanKanojia do you have an idea how the kubernetes-client handles CRDs ?

**Comment by rohanKanojia** [comment] 2018-09-12 11:16
Not sure if loading CustomResource is still supported or not. There is one [CRDExample.java](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/CRDExample.java) which demonstrates CRD usage support in client

**Comment by rhuss** [comment] 2018-12-11 16:20
I keep this issue open, as we need a strategy for dealing with custom resources in an untyped fashion.

**Comment by rohanKanojia** [comment] 2019-05-05 11:13
Duplicate of #1591

**Comment by rohanKanojia** [comment] 2019-05-05 11:15
@ryandawsonuk: Sorry for late reply, I missed this somehow. Yeah, you can deal with custom resources now in Fabric8 Kubernetes client. Please checkout [this](https://github.com/fabric8io/kubernetes-client/blob/master/kubernetes-examples/src/main/java/io/fabric8/kubernetes/examples/RawCustomResourceExample.java) example

**Comment by rohanKanojia** [comment] 2019-08-05 08:30
I think we have support for custom resources now.

**Comment by rohanKanojia** [comment] 2019-11-04 07:11
we already have support for custom resources. Please see this sample project for reference:

https://github.com/r0haaaan/fabric8-maven-plugin-sample-with-crds

**Closed by rohanKanojia** 2019-11-04 07:11 UTC

**Comment by jsjjdzg** [comment] 2019-11-05 01:55
Thank you very much！

**Comment by johnoraclestites** [comment] 2020-06-03 19:01
Is there support for something like what's mentioned by @ryandawsonuk in https://github.com/fabric8io/fabric8-maven-plugin/issues/1377#issuecomment-459969325 using .load() to load resources that are unknown to my operator? The examples all presume that the crd is known by the client and the client.customResources(crdContext) is the method of loading them. But our entire usage of the fabric8 client is to load yaml containing any and all k8s types and then using the object model to inspect them and modify them before pushing to the cluster. If we can't load the generic yaml then we don't know we have a custom resource that needs context. It would be very helpful if the client did something for unknown types like loading it into an UnknownTypeResource and letting a consumer inspect its properties instead of raising a json parse exception

**Comment by github-edu** [comment] 2020-07-23 02:48
```java
CustomResourceDefinition alertRuleDefinition = client.customResourceDefinitions().load(CrdTest.class.getResourceAsStream("/crd/alert-rule.yml")).get();
        System.out.println(alertRuleDefinition);
        CustomResourceDefinition result = client.customResourceDefinitions().create(alertRuleDefinition);
        System.out.println(result);
```


```yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-k8s-rules-lizw1
  namespace: monitoring
spec:
  groups:
    - name: pod.rules
      rules:
        - alert: pod_cpu_too_high
          annotations:
            message: Pod {{ $labels.instance }} with CPU too high
          expr: |
            rate (container_cpu_usage_seconds_total{image!="", container!="POD"}[5m])  > 0.01
          for: 1m
          labels:
            severity: critical
```


```
Exception in thread "main" io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://10.16.16.33:6443/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions. Message: PrometheusRule in version "v1" cannot be handled as a CustomResourceDefinition: no kind "PrometheusRule" is registered for version "monitoring.coreos.com/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:54". Received status: Status(apiVersion=v1, code=400, details=null, kind=Status, message=PrometheusRule in version "v1" cannot be handled as a CustomResourceDefinition: no kind "PrometheusRule" is registered for version "monitoring.coreos.com/v1" in scheme "k8s.io/apiextensions-apiserver/pkg/apiserver/apiserver.go:54", metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=BadRequest, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:568)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:507)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:471)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:430)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:251)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:844)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:352)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:79)
	at com.primeton.caas.fabric.CrdTest.main(CrdTest.java:16)
```

**Comment by github-edu** [comment] 2020-07-23 02:49
```bash
[root@node1 ~]# kubectl api-resources | grep prometheus
prometheuses                                   monitoring.coreos.com          true         Prometheus
prometheusrules                                monitoring.coreos.com          true         PrometheusRule
[root@node1 ~]# 
```

**Comment by rohanKanojia** [comment] 2020-07-23 06:54
@github-edu : You're loading a `CustomResource` into a `CustomResourceDefinitionObject`. Please have a look at fabric8 docs on how to deal with Custom Resources:

https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typeless-api

https://github.com/fabric8io/kubernetes-client/blob/master/doc/CHEATSHEET.md#customresource-typed-api
