### ISSUE TITLE
decouple regression tests from fabric8 maven plugin source

### ISSUE THREAD

**Issue by hrishin** [fabric8io/fabric8-maven-plugin#1306] opened 2018-06-13 05:40 UTC
Small change in booster application is breaking regression tests. Inherntly regression tests should run PR changes on F8-M-P, boosters applications both. 

Its better to move `regression test` module to other repo in fabric8 Github org and evaluate the way to tigger the tests. 

cc: @rohanKanojia @piyush1594

**Comment by rohanKanojia** [comment] 2018-06-13 05:43
Duplicate of  #1155

**Comment by rohanKanojia** [comment] 2018-06-13 05:49
Closing as duplicate

**Closed by rohanKanojia** 2018-06-13 05:49 UTC
Labels: Refactoring
