### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by plord12** [fabric8io/fabric8-maven-plugin#1768] opened 2019-12-11 17:14 UTC
When we get an error, we see the less than helpful `Failed to execute the build`.

I think functions like buildAndTag() need to display the underlying cause :

`
throw new MojoExecutionException("Failed to execute the build: " + ex.getCause());
`

**Comment by rohanKanojia** [comment] 2019-12-12 08:16
Hmm, I agree our build error messages don't give a clear idea of build failure. But sometimes root cause of failure is more difficult to track than just failure message from Kubernetes API. For example, We used to face a `SocketTimeoutException` in our build pipelines, but after investigation we found that S2I process wasn't able to spin build pod due to memory constraints.

**Comment by plord12** [comment] 2019-12-12 09:58
Here is an example.

Before -

```
[ERROR] F8: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image
```

After -

```

```

**Comment by rohanKanojia** [comment] 2019-12-12 10:08
@plord12 : Did you close this by accident? Or did I misunderstood your issue?

**Comment by plord12** [comment] 2019-12-12 10:40
Ugg, sorry, mouse went a bit mad.  Re-opening.

**Comment by plord12** [comment] 2019-12-12 10:41
An example I see is -

```
[ERROR] F8: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image
```

With use getCause() -

```
[ERROR] F8: Failed to execute the build: io.fabric8.maven.core.service.Fabric8ServiceException: Error while trying to build the image org.apache.maven.plugin.MojoExecutionException: Failed to create assembly for docker image  (with mode 'dir'): Error creating assembly archive docker: Problem copying files : /Users/plord/workspace/pipelinetest/ams/target/docker/ams/1.6.0-SNAPSHOT/build/maven/./tibco/sb-cep/10.6/ams/3rdparty/linux/nicstat/1.22_x86_64/nicstat.c (Permission denied).
```

**Comment by rohanKanojia** [comment] 2019-12-12 10:54
@plord12 : Hmm, `getCause()` does seem to give improvements in message. Would you like to create a quick PR to fix this issue?

**Closed** 2020-01-17 10:03 UTC
Labels: group/build
