### ISSUE TITLE
WildFly Swarm based applications do not work FMP

### ISSUE THREAD

**Issue by rareddy** [fabric8io/fabric8-maven-plugin#1173] opened 2018-02-05 16:15 UTC
This is a regression of https://github.com/fabric8io/fabric8-maven-plugin/issues/320

I tested with 3.5.34 version of FMP, the last version this worked is with 3.5.25

**Comment by Ladicek** [comment] 2018-02-27 18:10
We (WildFly Swarm team) are seeing the issue as well, see https://issues.jboss.org/browse/SWARM-1859

As I describe in that issue, I believe this started hapenning in FMP 3.5.34 (i.e. 3.5.33 works fine -- could you verify?), and the reason isn't a regression of #320 (#320 was caused by Jolokia Java agent, and that has been fixed since Jolokia 1.3.6). The reason is actually caused by the Prometheus Java agent, which was newly added in the Fabric8 Java S2I image 2.1.

I believe that until the Prometheus Java agent is fixed (similarly to how the Jolokia Java agent was fixed), FMP should just switch it off by setting the `AB_PROMETHEUS_OFF` environment variable.

**Comment by Ladicek** [comment] 2018-02-27 18:15
Submitted https://github.com/fabric8io/fabric8-maven-plugin/pull/1216

**Comment by rhuss** [comment] 2018-03-01 10:43
In order to fix this for Prometheus, the [jmx_exporter](https://github.com/prometheus/jmx_exporter) needs to adapt its initialization behaviour. It suffers from the same problem as Jolokia did since they switched to the JVM internal Java HTTP server which uses jul logging early before the JBoss log subsystem is setup (as jmx_exporter is also designed as  JVM agent which kicks in early).

The fix within Jolokia was quite involved, requiring some internal lifecycle changes, so not sure how easy and, even more important, whether the Prometheus folks are willing to change this for Wildfly. Tbh, I still believe this is a Wildfly issue, not that of the agents. In call always be that any JVM agent (e.g. also profiler) use java.util.logging which will cause this symptoms: Its not correct from Wildfly to assume its the first one hitting java.util.logging. 

I raised these concerns earlier on the original Jolokia related tickets, but they told me, its easier to it is easier for a camel to go through the eye of a needle than to get such a change into Widlfly. So we changed Jolokia, but you still have this issue for any other JVM agent.

**Comment by Ladicek** [comment] 2018-03-01 11:06
Personally, I'd rather abstain from such discussion, because I can see the pain on both sides. I just think that we should disable the Prometheus agent for WildFly Swarm applications for the time being :-)

**Comment by rhuss** [comment] 2018-03-01 12:24
np for me ;-) 

btw, for Jolokia 2 I plan some Prometheus support, so might be a long term solution, too :)

**Comment by Ladicek** [comment] 2018-03-01 13:04
The less agents, the better :-)

**Comment by piyush1594** [comment] 2018-03-13 09:26
Fixed by #1216 

@Ladicek Are we good to close this too.

**Comment by Ladicek** [comment] 2018-03-13 09:31
I believe that indeed this is fixed by #1216, so this can be closed.

**Comment by piyush1594** [comment] 2018-03-13 09:36
@hrishin @rohanKanojia @rhuss Closing this as #1216 will fix this.

**Closed by piyush1594** 2018-03-13 09:36 UTC
