### ISSUE TITLE
ClusterRole and ClusterRoleBinding not included for Kubernetes

### ISSUE THREAD

**Issue by xadhatter** [fabric8io/fabric8-maven-plugin#1378] opened 2018-09-13 01:24 UTC
### Description
When using resource fragment files the plugin does not include ClusterRole and ClusterRoleBinding for Kubernetes, only for OpenShift
### Info

* f-m-p version : 3.5.41
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: C:\Program Files\apache-maven-3.5.3\bin\..
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_181\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
* If it's a bug, how to reproduce : include clusterrole.yml and run mvn fabric8:resource
* Sample output:
```
[INFO] --- fabric8-maven-plugin:3.5.41:resource (default-cli) @ test-service ---
[INFO] F8: Running in Kubernetes mode
[INFO] F8: using resource templates from C:\Workspace\test-service\src\main\fabric8
Trying internal type for name:ClusterRole
Trying internal type for name:Deployment
Trying internal type for name:ServiceAccount
Trying internal type for name:Service
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\openshift\test-service-clusterrole.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\openshift\test-service-deploymentconfig.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\openshift\test-service-sa.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\openshift\test-service-svc.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\kubernetes\test-service-deployment.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\kubernetes\test-service-sa.yml resource
[INFO] F8: validating C:\Workspace\test-service\target\classes\META-INF\fabric8\kubernetes\test-service-svc.yml resource
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.394 s
[INFO] Finished at: 2018-09-12T20:36:56-04:00
[INFO] ------------------------------------------------------------------------
```

**Comment by xadhatter** [comment] 2018-09-14 00:00
@rohanKanojia Thanks for the quick response.  I tried the above using kubernetes-client v3.2.0 but it does not compile.  The client.rbac() method is not present.

**Comment by rohanKanojia** [comment] 2018-09-14 05:40
@xadhatter : ClusterRole support is not present in v3.2.0 as far as I know, try using v4.0.5(latest version). Oh, sorry for the confusion. Current master has diverged towards fmp 4.0.x, which contains latest kubernetes client as dependency. We would make a release once we get this branch stable, but it contains some breaking changes. You can try using SNAPSHOT version of fmp and check if it works for you.

**Comment by xadhatter** [comment] 2018-09-14 11:39
@rohanKanojia Gotcha.  I have a work-around for the time being.  I eagerly await a stable release of 4.0.x.

Thanks again for the quick responses and keep up the great work on this project, it's been super useful!

**Comment by rohanKanojia** [comment] 2018-10-05 18:35
@xadhatter : Closing this issue for the time being. We are going to release first version of 4.x soon ;-)

**Comment by Kuvaldis** [comment] 2018-11-20 11:19
@rohanKanojia, experienced the same issue with 3.5.41 and currently with 4.0.0-M1. The problem is not in the client, but in ResourceMojo itself. isOpenshiftItem method is implemented the way that it returns true if there is "openshift" in the item's package name. Exactly the case for ClusterRole and ClusterRoleBinding.
```java
private KubernetesList removeOpenShiftObjects(KubernetesList list) {
        KubernetesListBuilder ret = new KubernetesListBuilder();
        ret.withMetadata(list.getMetadata());
        for (HasMetadata item : list.getItems()) {
            if (!isOpenshiftItem(item)) { // here I see the problem
                ret.addToItems(item);
            } else {
                log.verbose("kubernetes.yml: Removed OpenShift specific resource '%s' of type %s",
                    KubernetesHelper.getName(item), KubernetesHelper.getKind(item));
            }
        }
        return ret.build();
    }
```

**Comment by johanra** [comment] 2019-02-01 12:47
@rohanKanojia Can you reopen this issue as it still exists using 4.0.0-M2?
Next to the previously mentioned ClusterRole and ClusterRoleBinding also Role is not included in the kubernetes.yml while these are present in the openshift file.
As mentioned by @Kuvaldis the problem is in the ResourceMojo where openshift vs. Kubernetes is decided based on a java package name from the kubernetes-model library

private boolean isOpenshiftItem(HasMetadata item) {
        if (isTargetPlatformOpenShift(item)) {
            return true;
        }
        return item.getClass().getPackage().getName().contains("openshift");
    }

I am running a fork that changes the implementation to look at the apiversion instead.
private boolean isOpenshiftItem(HasMetadata item) {
        if (isTargetPlatformOpenShift(item)) {
            return true;
        }
        return item.getApiVersion().contains("openshift");	
    }
In my case this resolves the issue because I explicitly mention the apiversion in my resource fragments
for example role.yml has apiVersion: rbac.authorization.k8s.io/v1

**Comment by rohanKanojia** [comment] 2019-06-20 09:09
@xadhatter @johanra : I tried reproducing it on FMP 4.1.0, but could not. I added these resource fragments in my `src/main/fabric8` directory:
```
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ cat src/main/fabric8/cluster-role.yml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ cat src/main/fabric8/cluster-rolebinding.yml 
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: Group
  name: manager # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```

But after running fmp goals, I was able to see ClusterRole/ClusterRoleBinding resources being created on Kubernetes cluster. Did I reproduce it correctly? Or did I miss something? Here are my logs:
```
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:36:19Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ ls src/main/fabric8/
cluster-rolebinding.yml  cluster-role.yml  deployment.yml  raw  service.yml
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ mvn clean install fabric8:build fabric8:resource fabric8:deploy
[INFO] Scanning for projects...
[INFO] 
[INFO] -------< io.fabric8:fabric8-maven-sample-spring-boot-with-yaml >--------
[INFO] Building Fabric8 Maven :: Sample :: Spring Boot Web 4.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Deleting /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/resources
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Building jar: /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.3.6.RELEASE:repackage (default) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/pom.xml to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.pom
[INFO] 
[INFO] --- fabric8-maven-plugin:4.1.0:build (default-cli) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] F8: Running in Kubernetes mode
[INFO] F8: Building Docker image in Kubernetes mode
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-centos-openjdk8-jdk:1.5 as base / builder
[INFO] Copying files to /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/docker/fabric8/fabric8-maven-sample-spring-boot-with-yaml/latest/build/maven
[INFO] Building tar: /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/docker/fabric8/fabric8-maven-sample-spring-boot-with-yaml/latest/tmp/docker-build.tar
[INFO] F8: [fabric8/fabric8-maven-sample-spring-boot-with-yaml:latest] "spring-boot": Created docker-build.tar in 145 milliseconds
[INFO] F8: [fabric8/fabric8-maven-sample-spring-boot-with-yaml:latest] "spring-boot": Built image sha256:eee9b
[INFO] F8: [fabric8/fabric8-maven-sample-spring-boot-with-yaml:latest] "spring-boot": Removed old image sha256:97408
[INFO] F8: [fabric8/fabric8-maven-sample-spring-boot-with-yaml:latest] "spring-boot": Tag with latest
[INFO] 
[INFO] --- fabric8-maven-plugin:4.1.0:resource (default-cli) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/java-centos-openjdk8-jdk:1.5 as base / builder
[INFO] F8: using resource templates from /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/fabric8
[INFO] F8: f8-healthcheck-spring-boot: Adding readiness probe on port 8080, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: f8-healthcheck-spring-boot: Adding liveness probe on port 8080, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes/secret-reader-clusterrole.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes/read-secrets-global-clusterrolebinding.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes/password-secret.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes/fabric8-maven-sample-spring-boot-with-yaml-service.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes/fabric8-maven-sample-spring-boot-with-yaml-deployment.yml resource
[INFO] F8: using resource templates from /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/fabric8
[INFO] F8: f8-healthcheck-spring-boot: Adding readiness probe on port 8080, path='/health', scheme='HTTP', with initial delay 10 seconds
[INFO] F8: f8-healthcheck-spring-boot: Adding liveness probe on port 8080, path='/health', scheme='HTTP', with initial delay 180 seconds
[INFO] F8: fmp-revision-history: Adding revision history limit to 2
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/fabric8-maven-sample-spring-boot-with-yaml-route.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/secret-reader-clusterrole.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/read-secrets-global-clusterrolebinding.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/password-secret.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/fabric8-maven-sample-spring-boot-with-yaml-service.yml resource
[INFO] F8: validating /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift/fabric8-maven-sample-spring-boot-with-yaml-deploymentconfig.yml resource
[INFO] 
[INFO] >>> fabric8-maven-plugin:4.1.0:deploy (default-cli) > install @ fabric8-maven-sample-spring-boot-with-yaml >>>
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/resources
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] No tests to run.
[INFO] Skipping execution of surefire because it has already been run for this configuration
[INFO] 
[INFO] --- maven-jar-plugin:2.5:jar (default-jar) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Building jar: /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar
[INFO] 
[INFO] --- spring-boot-maven-plugin:1.3.6.RELEASE:repackage (default) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.jar
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/pom.xml to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT.pom
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes.yml to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT-kubernetes.yml
[INFO] Installing /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/openshift.yml to /home/rohaan/.m2/repository/io/fabric8/fabric8-maven-sample-spring-boot-with-yaml/4.1-SNAPSHOT/fabric8-maven-sample-spring-boot-with-yaml-4.1-SNAPSHOT-openshift.yml
[INFO] 
[INFO] <<< fabric8-maven-plugin:4.1.0:deploy (default-cli) < install @ fabric8-maven-sample-spring-boot-with-yaml <<<
[INFO] 
[INFO] 
[INFO] --- fabric8-maven-plugin:4.1.0:deploy (default-cli) @ fabric8-maven-sample-spring-boot-with-yaml ---
[INFO] F8: Using Kubernetes at https://192.168.99.100:8443/ in namespace default with manifest /home/rohaan/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml/target/classes/META-INF/fabric8/kubernetes.yml 
[INFO] F8: Using namespace: default
[INFO] F8: Using namespace: default
[INFO] F8: Updating a Secret from kubernetes.yml
[INFO] F8: Updated Secret:target/fabric8/applyJson/default/secret-password.json
[INFO] F8: Creating a Service from kubernetes.yml namespace default name fabric8-maven-sample-spring-boot-with-yaml
[INFO] F8: Created Service: target/fabric8/applyJson/default/service-fabric8-maven-sample-spring-boot-with-yaml.json
[INFO] F8: Applying ClusterRole secret-reader from kubernetes.yml
[INFO] F8: Applying ClusterRoleBinding read-secrets-global from kubernetes.yml
[INFO] F8: Creating a Deployment from kubernetes.yml namespace default name fabric8-maven-sample-spring-boot-with-yaml
[INFO] F8: Created Deployment: target/fabric8/applyJson/default/deployment-fabric8-maven-sample-spring-boot-with-yaml.json
[INFO] F8: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.464 s
[INFO] Finished at: 2019-06-20T14:36:00+05:30
[INFO] ------------------------------------------------------------------------
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ oc get clusterrole secret-reader
NAME            AGE
secret-reader   12m
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $ kubectl get clusterrolebinding read-secrets-global
NAME                  AGE
read-secrets-global   12m
~/work/repos/fabric8-maven-plugin/samples/spring-boot-with-yaml : $
```

**Comment by rohanKanojia** [comment] 2019-06-20 09:10
I'm closing this for now, feel free to re-open it in case it's reproducible.

**Closed by rohanKanojia** 2019-06-20 09:10 UTC

**Comment by rohanKanojia** [comment] 2019-06-20 10:06
@dev-gaur : Could you please confirm on your side as well? Sorry, I didn't see you were working on this.

**Comment by seboudry** [comment] 2020-01-16 11:10
Hi!
I reproduce this issue using f-m-p 3.5.42 but not on 4.X.

Output of `mvn fabric8:resource`:
```
[INFO] F8: using resource templates from /home/me/dev/my-app/service/src/main/fabric8
Trying internal type for name:RoleBinding
Trying internal type for name:ServiceAccount
Trying internal type for name:ConfigMap
Trying internal type for name:Deployment
Trying internal type for name:Role
[...]
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-route.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-configmap.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-rolebinding.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-svc.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-deploymentconfig.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-sa.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/openshift/my-app-role.yml resource
[INFO] F8: kubernetes.yml: Removed OpenShift specific resource 'my-app' of type Role
[INFO] F8: kubernetes.yml: Removed OpenShift specific resource 'my-app' of type RoleBinding
[INFO] F8: kubernetes.yml: Removed OpenShift specific resource 'my-app' of type Route
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/kubernetes/my-app-deployment.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/kubernetes/my-app-configmap.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/kubernetes/my-app-svc.yml resource
[INFO] F8: validating /home/me/dev/my-app/service/target/classes/META-INF/fabric8/kubernetes/my-app-sa.yml resource
```

I'm sure proposed solution by @johanra would fix this: https://github.com/fabric8io/fabric8-maven-plugin/issues/1378#issuecomment-459711977

As I'm stuck with 3.X versions waiting for #1776, this issue is blocking :(

**Comment by rohanKanojia** [comment] 2020-01-20 10:33
@seboudry : oh, you mean #1776 is blocking you to upgrade to 4.x versions?
